### ISSUE TITLE
怎么使用，有没有简单demo,没有返回知道连接情况

### ISSUE THREAD

**Issue by umena337** [daishuai/stomp-ws#1]

**Comment by daishuai** [comment]
> _No description provided._

可以看下这个 https://www.jianshu.com/p/1aed8a67ce95

**Comment by daishuai** [comment]
@umena337 可以看下这篇文章里面有demo https://www.jianshu.com/p/1aed8a67ce95

建立连接的时候可以传一个回调函数，connect_callback
